org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.configureondemand=false
android.useAndroidX=true
android.enableJetifier=true
systemProp.http.connectTimeout=60000
systemProp.http.socketTimeout=60000
