// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmrdyUv8Kb4qXJWj2CgxQ7kXZivj6uVUY',
    appId: '1:707806279505:web:07c8d88cf3888773768570',
    messagingSenderId: '707806279505',
    projectId: 'notifications-eea02',
    authDomain: 'notifications-eea02.firebaseapp.com',
    storageBucket: 'notifications-eea02.firebasestorage.app',
    measurementId: 'G-9Y2G64YK66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl_juB7LIpAkuJaYL-Yxy6pEXDZkfkyUU',
    appId: '1:707806279505:android:daf03e86054b632a768570',
    messagingSenderId: '707806279505',
    projectId: 'notifications-eea02',
    storageBucket: 'notifications-eea02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqUxBr8_TMaWsfwOc-BTVH5hcd-jfFF6s',
    appId: '1:707806279505:ios:bbb2f2cec3cc02cf768570',
    messagingSenderId: '707806279505',
    projectId: 'notifications-eea02',
    storageBucket: 'notifications-eea02.firebasestorage.app',
    iosBundleId: 'com.ahmed.Equiphorse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqUxBr8_TMaWsfwOc-BTVH5hcd-jfFF6s',
    appId: '1:707806279505:ios:af645412b5b867b9768570',
    messagingSenderId: '707806279505',
    projectId: 'notifications-eea02',
    storageBucket: 'notifications-eea02.firebasestorage.app',
    iosBundleId: 'com.example.fixedEquiphorse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmrdyUv8Kb4qXJWj2CgxQ7kXZivj6uVUY',
    appId: '1:707806279505:web:beaf5f8baae5dd6c768570',
    messagingSenderId: '707806279505',
    projectId: 'notifications-eea02',
    authDomain: 'notifications-eea02.firebaseapp.com',
    storageBucket: 'notifications-eea02.firebasestorage.app',
    measurementId: 'G-HEGKJ2EFZY',
  );

}